require 'trigram_analyzer'
require 'trigram_generator'

text = "I was accused recently of believing things I don't believe about women as programmers and startup founders. So I thought I'd explain what I actually do believe.

Some accused me of being sexist—of being biased against female founders. To anyone who knows Y Combinator that would seem a pretty implausible claim. It's hard to argue I'm biased against female founders when I have a female cofounder myself. And with 3 female partners out of 12, YC has slightly over 3x the venture industry average. While 3 out of 12 is not 50-50, it would be very hard to find another firm of our size in the venture business where women run the show to the degree they do at YC. I may be the public face of the company, but it's impossible to imagine YC doing something that Jessica, Kirsty, and Carolynn were against.

More thoughtful people were willing to concede YC wasn't biased against women, but thought we should be actively working to increase the number of female founders. As one put it, instead of being a gatekeeper, we should be a gateway.

But that is exactly what Y Combinator is. The people who caricature us as being only interested in funding young hotshots forget that when we started, in 2005, young founders were not a privileged group but a marginalized one. VCs didn't want to fund them, and when they did they often as not tried to replace them with 'adult supervision.' The fact that young founders seem a privileged group now is partly due to our efforts. We attacked the problem not by advocacy but by action—by funding more young founders than VCs would, and then helping them to overcome the bias against them that they'd encounter among other investors. It worked rapidly, because it had a double effect: if you support a young founder who otherwise would not have been able to find funding and they go on to succeed, you get not just one more young founder but also the additional ones they inspire by their example.

We're doing the same thing for female founders. We fund more female founders than VCs do, and we help them to overcome the bias they'll encounter among other investors. In the current YC batch, 16 out of 68 companies, or 24%, have female founders. That's almost twice the rate at which VCs fund such companies. If these founders go on to succeed, they'll become what we know from experience will be the most powerful force for encouraging other female founders: examples of people like them who've done it.

The way we got so many female founders was by being less biased. It was the same with young founders. We didn't lower our standards for younger founders. We just tried to be better than other investors at seeing their true potential. That's why it worked.

Is there another organization that has done more to help female founders than Y Combinator, measured by number of female founders helped times how much we've helped each one? Possibly. But the amount of thought it takes to answer that question shows we are at least among the organizations that have done most.

Eventually other investors will follow our lead. I can say more than that I hope they will, because as with young founders, they will make more money if they do, and investors tend to notice that fairly quickly. A lot of people outside the startup world seem to assume that investors have the same sort of naive bias ordinary people do when deciding who to invite to join a club—that they simply fund the people most like them. That is not true. What drives most investors is money. As it should, because they have a fiduciary duty to their limited partners. So while they have biases, their biases are merely instances of stupidity, not principles they feel they have to uphold. When they realize they've been overlooking some type of startup or founder, they stop, because it means they've been losing money. All it takes is another investor who's willing to fund the companies they're overlooking.

I saw this happen with Homejoy. When Adora Cheung first tried to raise a series A round, she couldn't find a VC willing to lead, despite their remarkable growth. Partly this was due to the nature of the business. Software-eating-the-world startups are still a novel idea to many investors. But I was convinced it was also partly because Adora was female. So I tweeted their revenue graph, saying that this was the fastest growing YC company I knew of, because I knew ultimately growth was what would convince investors. As in fact it did. If your numbers go up steeply enough for long enough, you could have eyeballs on stalks and investors will fund you.

I realize though that with female founders, efforts at our stage are not enough. We could in principle have fixed the problem for young founders by ourselves. If we funded enough young founders who went on to succeed, both investors and other would-be founders would learn from their example. But it would be naive to assume we could get the percentage of female startup founders to 50% so long as the percentage of female programmers is so much lower than 50%. Though this is less the case than it used to be, many startups still have a big technical component, and if you want to start that sort of startup your chances of succeeding are higher if you're a programmer. Adora Cheung is a programmer, for example. Software eating the world is still software.

So how would you cause there to be more female programmers? The meta-answer is: not just one thing. People's abilities and interests by the time they're old enough to start a startup are the product of their whole lives—indeed, of their ancestors' lives as well. Even if we limit ourselves to one lifetime we find a long list of factors that could influence the ratio of female programmers to male, from the first day of a girl's life when her parents treat her differently, right up to the point where a woman who has become a programmer leaves the field because it seems unwelcoming. And while the nature of this sort of funnel is that you can increase throughput by attacking bottlenecks at any point, if you want to eliminate the discrepancy between male and female programmers completely, you probably have to go back to the point where it starts to become significant.

It seems to be well underway by the time kids reach their teens. Which to me suggests the place to focus the most effort initially is in getting more girls interested in programming.

I'm not saying that's the only thing you could do, or trying to downplay other obstacles women and girls face in becoming programmers or founders. I'm just saying that seems to me where you'd get the most bang for the buck.

How would you get more girls interested in programming? I don't know much about girls specifically, but I have some ideas about how to get kids interested in programming. I think at a minimum you need two things: access and examples.

First of all, kids need to be able to program, in both senses of the word: they have to know how to write a program, and they need access to a computer they can write programs on, which nowadays probably includes Internet connectivity.

But to turn kids into avid programmers—to get them to work on projects of their own in their spare time—you may need to do more than just expose them to programming. In my experience the best way to get people to work on ambitious projects is examples of other people who have. I'm pretty sure that's why so many more startups come out of some universities than others, for example. I don't think Yale students are inherently less able to start startups than Stanford students, or that Yale doesn't prepare them to. They just don't have examples of successful startups all around them like Stanford students do.

So if we want to get more girls to become programmers, we should give them more examples. Ideally in person, though examples also work through the media. Do the examples have to be female? They don't have to be to send the message that programming is one of the things people can work on, but female programmers might make more compelling role models.

Are there other things you could do to get girls interested in programming? Almost certainly. Are there other things you'd have to do? Quite possibly. But notice the language I'm using. In the course of writing this I've gone from certainty to uncertainty. That's because I've gone from talking about a topic I know more about than most people—what happens when women start startups—to a topic many people know more about than me.

I can say though that at our end of the funnel the trend for female founders is encouraging. Not just because 24% of the companies in the current YC batch have female founders. There is also starting to be a critical mass of successful female founders from previous batches, which means we can now run events like the one Jessica is organizing in which they share their experiences with other women interested in starting startups. That should further accelerate the growing number who do."

patterns = TrigramAnalyzer.analyze_text(text)
new_text = TrigramGenerator.generate_text(patterns)
puts new_text
